=== maxhagn/SemiStructuredData/Semi 02/ssd-exercise2-ss20/resources/art.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="art">
        <xs:complexType>
            <xs:all>
                <xs:element name="artists">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="artist">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="lived">
                                            <xs:complexType>
                                                <xs:attribute name="from" type="xs:date"/>
                                                <xs:attribute name="to" type="xs:date"/>
                                                <xs:attribute name="birthplace" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tags">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="1">
                                                  <xs:element maxOccurs="3" minOccurs="0" name="t"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                            <xs:key name="artistTagKey">
                                                <xs:selector xpath="./t"/>
                                                <xs:field xpath="."/>
                                            </xs:key>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="aid" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="objects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="3" name="object">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="kind">
                                            <xs:complexType>
                                                <xs:choice>
                                                  <xs:element name="painting">
                                                  <xs:complexType>
                                                  <xs:attribute name="paint" use="optional">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                      <xs:enumeration value="Oil"/>
                                                      <xs:enumeration value="Acrylic"/>
                                                      <xs:enumeration value="Chalk"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:attribute>
                                                  <xs:attribute name="on">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string"/>
                                                  </xs:simpleType>
                                                  </xs:attribute>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="sculpture">
                                                  <xs:complexType>
                                                  <xs:attribute name="material" type="xs:string"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="label">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                  <xs:choice maxOccurs="unbounded">
                                                  <xs:element name="by" type="xs:string"/>
                                                  <xs:element name="year" type="xs:int"/>
                                                  <xs:element name="ref" minOccurs="0"
                                                  maxOccurs="unbounded">
                                                  <xs:complexType>
                                                  <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="aid" type="xs:string"/>
                                                  <xs:attribute name="t" type="xs:string"/>
                                                  </xs:extension>
                                                  </xs:simpleContent>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:choice>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element maxOccurs="1" minOccurs="1" name="catalog">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([A-Z]){2}-([0-9]){3}-([a-z][0-9]){1}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="tags">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="3" minOccurs="0" name="t"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                            <xs:unique name="objectTagKey">
                                                <xs:selector xpath="./t"/>
                                                <xs:field xpath="."/>
                                            </xs:unique>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tags">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="tag">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="tagname" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
        <xs:key name="artistKey">
            <xs:selector xpath="artists/artist"/>
            <xs:field xpath="@aid"/>
        </xs:key>
        <xs:key name="tagKey">
            <xs:selector xpath="tags/tag"/>
            <xs:field xpath="@tagname"/>
        </xs:key>
        <xs:key name="objKey">
            <xs:selector xpath="objects/object"/>
            <xs:field xpath="title"/>
            <xs:field xpath="catalog"/>
        </xs:key>
        <xs:keyref name="artistRef" refer="artistKey">
            <xs:selector xpath="ref"/>
            <xs:field xpath="@aid"/>
        </xs:keyref>
        <xs:keyref name="tagRef" refer="tagKey">
            <xs:selector xpath="tags"/>
            <xs:field xpath="t"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== maxhagn/SemiStructuredData/2. Assignment/template/template/resources/art-sample-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<art xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="art.xsd">
  <artists>
    <artist aid="0">
      <name>Pablo Picasso</name>
      <lived from="1881-10-25" to="1973-04-07" birthplace="Spain"/>
      <tags>
	<t>Picasso</t>
	<t>Spain</t>
      </tags>
    </artist>
  </artists>
  
  <objects>
    <object>
      <title>Mediteranean Landscape</title>
      <kind><painting paint="Oil" on="canvas"/></kind>
      <label>
	The painting was painted by <by>Pablo Picasso</by> and and finished by <year>1952</year>.
	An early example of Picassos cubism who he developed alongside <ref aid="0">George Braque</ref>
      </label>
      <catalog>PP-452-b1</catalog>
      <tags>
      </tags>
    </object>

    <object>
      <title>Tod und Leben</title>
      <kind><painting paint="Oil" on="Canvas"/></kind>
      <label>
	Painted by <by>Pablo Picasso</by> in different years: <year>1921</year> and <year>1952</year>.
      </label>
      <catalog>GK-230-t0</catalog>
      <tags>
	<t>Jugendstil</t>
      </tags>
    </object>

    <object>
      <title>Statue des hl. Leopold</title>
      <kind><sculpture material="stone"/></kind>
      <label>
	Eine von zwei Statuen auf der Kirche am Steinhof, eines der <year>1952</year>
	Hauptwerke des <ref>Jugendstil</ref>. Wie auch die Kirche von
	<by>Pablo Picasso</by> konzipiert.
      </label>
      <tags>
	<t>Jugendstil</t>
      </tags>
      <catalog>XY-234-x3</catalog>
    </object>
  </objects>
    
  <tags>
    <tag tagname="Cubism">
      Style of painting born in the early 20th century which abstracts
      by reducing subjects to geometric outlines.
    </tag>
    <tag tagname="Jugendstil">
    </tag>
    <tag tagname="Picasso">
    </tag>
    <tag tagname="Spain">
    </tag>
  </tags>
</art>

=== maxhagn/SemiStructuredData/Semi 02/template/template/resources/art-sample-out.xml
<art xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="art.xsd">
  <artists>
    <artist aid="0">
      <name>Pablo Picasso</name>
      <lived birthplace="Spain" from="1881-10-25" to="1973-04-07"/>
      <tags>
	<t>Picasso</t>
	<t>Spain</t>
      </tags>
    </artist>
  </artists>
  
  <objects>
    

    <object>
      <title>Tod und Leben</title>
      <kind>
<painting on="Canvas" paint="Oil"/>
</kind>
      <label>
	Painted by <by>Gustav Klimt</by> in different years: <year>1921</year> and <year>1924</year>.
      </label>
      <catalog>GK-230-t0</catalog>
      <tags>
	<t>Jugendstil</t>
      </tags>
    </object>

    <object>
      <title>Statue des hl. Leopold</title>
      <kind>
<sculpture material="stone"/>
</kind>
      <label>
	Eine von zwei Statuen auf der Kirche am Steinhof, eines der
	Hauptwerke des <ref>Jugendstil</ref>. Wie auch die Kirche von
	<by>Otto Wagner</by> konzipiert.
      </label>
      <tags>
	<t>Jugendstil</t>
      </tags>
      <catalog>XY-234-x3</catalog>
    </object>
  <object>
<title>Mona Lisa</title>
<kind>
<painting on="panel" paint="Oil"/>
</kind>
<label>This object was created by <by>Leonardo di ser Piero da Vinci</by> in the year <year>1513</year>. The best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world.</label>
<catalog>EX-004-a0</catalog>
<tags>
<t>Renaissance</t>
<t>Italy</t>
</tags>
</object>
<object>
<title>David</title>
<kind>
<sculpture/>
</kind>
<label>This object was created by <by>Michelangelo di Lodovico Buonarroti Simoni</by> in the year <year>1504</year>. David is a masterpiece of Renaissance sculpture created in marble. David is a 5.17-metre (17.0 ft) marble statue of the Biblical hero David, a favoured subject in the art of Florence. </label>
<catalog>EX-004-a0</catalog>
<tags>
<t>Renaissance</t>
</tags>
</object>
<object>
<title>Black Square</title>
<kind>
<painting on="linen" paint="Oil"/>
</kind>
<label>This object was created by <by>Kazimir Malevich</by> in the year <year>1915</year>. This work is frequently invoked by critics, historians, curators, and artists as the "zero point of painting".</label>
<catalog>EX-004-a0</catalog>
<tags>
<t>Suprematism</t>
<t>Russia</t>
</tags>
</object>
</objects>
    
  <tags>
    <tag tagname="Cubism">
      Style of painting born in the early 20th century which abstracts
      by reducing subjects to geometric outlines.
    </tag>
    <tag tagname="Jugendstil">
    </tag>
    <tag tagname="Picasso">
    </tag>
    <tag tagname="Spain">
    </tag>
  <tag tagname="Renaissance"/>
<tag tagname="Italy"/>
<tag tagname="Suprematism"/>
<tag tagname="Russia"/>
</tags>
</art>
