=== maxhagn/SemiStructuredData/Semi 01/Semistrukturierte Daten 1/buchbestand-id.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="buchbestand">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="buch" type="buchType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="bestand" type="bestandType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	
		<xs:key name="buchid">
			<xs:selector xpath="buch"/>
			<xs:field xpath="@id"/>
		</xs:key>
		
		<xs:keyref name="buchref" refer="buchid">
			<xs:selector xpath="bestand"/>
			<xs:field xpath="@buch"/>
		</xs:keyref>
	</xs:element>
	
	<xs:complexType name="buchType">
		<xs:sequence>
			<xs:element name="titel" type="xs:string"/>
			<xs:element name="autor" type="xs:string"/>
			<xs:element name="seiten" type="xs:positiveInteger"/>
			<xs:element name="preis" type="xs:decimal"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="lagernd" type="xs:boolean" use="optional"/>
		<xs:attribute name="einband" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="bestandType">
		<xs:attribute name="buch" type="xs:IDREF" use="required"/>
		<xs:attribute name="lagernd" type="xs:boolean" use="required"/>
	</xs:complexType>
</xs:schema>

=== maxhagn/SemiStructuredData/Semi 01/Semistrukturierte Daten 1/buchbestand-with-schemalocation-id.xml
<?xml version="1.0" encoding="UTF-8"?>
<buchbestand xsi:noNamespaceSchemaLocation="buchbestand-id.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<buch einband="Taschenbuch" id="b1">
		<titel>The Adventures of Huckleberry Finn</titel>
		<autor>Mark Twain</autor>
		<seiten>336</seiten>
		<preis>12.75</preis>
	</buch>
	<buch einband="Taschenbuch" lagernd="true" id="b2">
		<titel>In der Strafkolonie</titel>
		<autor>Franz Kafka</autor>
		<seiten>125</seiten>
		<preis>9.90</preis>
	</buch>
	<buch einband="Gebundene Ausgabe" lagernd="false"  id="b3">
		<titel>Leaves of Grass</titel>
		<autor>Walt Whitman</autor>
		<seiten>462</seiten>
		<preis>25.00</preis>
	</buch>
	<buch einband="Taschenbuch" lagernd="false"  id="b4">
		<titel>The Legend of Sleepy Hollow</titel>
		<autor>Washington Irving</autor>
		<seiten>98</seiten>
		<preis>2.50</preis>
	</buch>
	<buch einband="Gebundene Ausgabe" lagernd="true"  id="b5">
		<titel>Der Graf von Monte Christo</titel>
		<autor>Alexandre Dumas</autor>
		<seiten>760</seiten>
		<preis>19.00</preis>
	</buch>
	<buch einband="Gebundene Ausgabe" lagernd="true"  id="b6">
		<titel>Moby-Dick</titel>
		<autor>Herman Melville</autor>
		<seiten>724</seiten>
		<preis>22.00</preis>
	</buch>
	<buch einband="Taschenbuch" lagernd="false"  id="b7">
		<titel>The Scarlet Letter</titel>
		<autor>Nathaniel Hawthorne</autor>
		<seiten>253</seiten>
		<preis>7.80</preis>
	</buch>
	<buch einband="Gebundene Ausgabe" lagernd="true"  id="b8">
		<titel>Harry Potter und der Stein der Weisen</titel>
		<autor>J.K. Rowling</autor>
		<seiten>335</seiten>
		<preis>12.00</preis>
	</buch>
	<buch einband="Taschenbuch" lagernd="true"  id="b9"> 
		<titel>Der Prozess</titel>
		<autor>Franz Kafka</autor>
		<seiten>217</seiten>
		<preis>13.80</preis>
	</buch>
	<bestand buch="b1" lagernd="true"/>
	<bestand buch="b9" lagernd="false"/>
	<bestand buch="b1" lagernd="false"/>
</buchbestand>
